MISSING_VALUE_CODES = ["-"]

Q1_CITESCORE_PERCENTILE_MAX = 25

CITESCORE_QUARTILE_BOUNDS = [0, 25, 50, 75, 100]
CITESCORE_QUARTILE_LABELS = ["Q1", "Q2", "Q3", "Q4"]

OVERPERFORMING_SOURCE_MIN_PUBLICATIONS = 10

HIGH_PERFORMING_PARTNER_MIN_PUBLICATIONS = 10

TOP_DECILE_PERCENTILE_MAX = 10

TOP_1_PERCENT_PERCENTILE_MAX = 1

CITATION_WINDOW_TRAILING_YEARS_EXCLUDED = 2

EXCLUDE_SELF_CITATIONS = False

INCLUDED_DOCUMENT_TYPES = None

EXCLUDE_RETRACTED = True

FRACTIONAL_FIELD_COUNTING = False

MAIN_YEAR_RANGE = (2020, 2024)

INTERNATIONAL_COLLABORATION_MIN_COUNTRIES = 2

INSTITUTIONAL_COLLABORATION_MIN_INSTITUTIONS = 2

OPEN_ACCESS_NULL_MEANS_NOT_OA = True

COLLABORATION_BREADTH_BINS = [0, 1, 2, 3]

SCENARIO_DEFAULT_DELTA_PP = 0.05

GO8_UNIVERSITIES = [
    "Adelaide University",
    "Australian National University",
    "Monash University",
    "The University of Sydney",
    "University of Melbourne",
    "University of New South Wales",
    "University of Queensland",
    "University of Western Australia",
]

CLIENT_UNIVERSITY = "The University of Sydney"
